name: Visit website using Firefox

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Enter the URL of the website to visit"
        required: true

jobs:
  visit-website:
    runs-on: ubuntu-latest
    steps:
    - name: Use Firefox web driver to visit website
      env:
        DISPLAY: :99.0
      run: |
        export MOZ_HEADLESS=1
        apt-get update
        apt-get install -y firefox-geckodriver xvfb
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo 'Starting Firefox ...'
        /usr/bin/firefox --version
        /usr/bin/firefox --headless --no-remote --marionette ${{ inputs.url }}
